# repo: (mô tả 1 dòng, CPU, fit-score, fit note, license note override)
N = {
"harry0703/MoneyPrinterTurbo": ("Chủ đề → kịch bản LLM → TTS → tự tìm footage Pexels/Pixabay theo keyword → phụ đề → BGM → render (MoviePy); WebUI/API/CLI", "✅ CPU", "★★★★", "Gần pipeline nhất. Mượn module tìm/ghép B-roll + timing phụ đề; thay TTS bằng OmniVoice; tự thêm PIP mặt", None),
"openai/whisper": ("ASR gốc của OpenAI (99 ngôn ngữ, có tiếng Việt)", "⚠️ CPU chậm (model large)", "★★", "Dùng bản tối ưu (faster-whisper/whisper.cpp) thay vì bản gốc", None),
"calesthio/OpenMontage": ("Hệ thống sản xuất video agentic: 12 pipeline, research→script→asset (stock/AI)→dựng bằng Remotion", "✅ CPU (gen model qua API)", "★★", "Tham khảo kiến trúc agent + kho footage free; nặng, AGPL (lây license nếu phân phối/dịch vụ)", None),
"remotion-dev/remotion": ("Dựng video bằng React (TSX) → MP4 qua headless Chromium; có @remotion/captions", "✅ CPU (chậm hơn ffmpeg, ~2–4GB RAM/luồng)", "★★★", "Mạnh nhưng trùng vai HyperFrames; license riêng: miễn phí cá nhân/công ty ≤3 người, lớn hơn phải mua", "Remotion License (source-available)"),
"heygen-com/hyperframes": ("HTML/CSS/GSAP → MP4 tất định, có CLI + skills cho AI agent (HeyGen)", "✅ CPU (headless Chrome + ffmpeg)", "★★★★★", "Đã là engine ưu tiên trong playbook; dùng cho layout 9:16, caption động, PIP mặt (thẻ <video> bo tròn), title card", None),
"ggml-org/whisper.cpp": ("Whisper bản C/C++, lượng tử hoá, rất nhanh trên CPU, xuất SRT/VTT/JSON có timestamp", "✅ CPU tốt", "★★★★", "Lựa chọn nhẹ nhất cho ASR/timestamp trên box; ít phụ thuộc Python", None),
"hpcaitech/Open-Sora": ("Model text/image-to-video Open-Sora 2.0 (11B)", "❌ GPU lớn (H100/H800, đa GPU)", "★", "Không chạy được trên box", None),
"ATH-MaaS/Pixelle-Video": ("Chủ đề → văn án → ảnh/video AI (ComfyUI/RunningHub/API) → TTS → BGM → ghép; có pipeline 数字人口播", "⚠️ Điều phối CPU, ảnh/video AI cần GPU/API", "★★", "Hướng 'ảnh AI minh hoạ', không phải tin tức + footage thật; tham khảo template", None),
"SYSTRAN/faster-whisper": ("Whisper chạy trên CTranslate2, int8 CPU nhanh ~4x, có word_timestamps", "✅ CPU (small/medium int8)", "★★★★", "Lõi ASR cho clip nguồn/QA; nền của WhisperX", None),
"m-bain/whisperX": ("faster-whisper + forced alignment wav2vec2 → timestamp từng từ chính xác (+diarization)", "✅ CPU (int8, chậm hơn GPU)", "★★★★★", "Có align model tiếng Việt; dùng hàm align() với KỊCH BẢN ĐÃ BIẾT + wav OmniVoice → word-level SRT chuẩn, không lo ASR sai chính tả", None),
"motion-canvas/motion-canvas": ("Thư viện animation bằng TypeScript + editor realtime", "✅ CPU", "★★", "Hợp motion graphics; render headless kém (dùng Revideo nếu cần)", None),
"KlingAIResearch/LivePortrait": ("Animate ảnh/video chân dung theo video driving (biểu cảm, đầu); không phải audio-driven", "⚠️ GPU khuyến nghị (CPU rất chậm)", "★", "Ta có clip presenter quay sẵn nên không cần; code MIT nhưng dùng model InsightFace (phi thương mại)", "MIT (code) + model InsightFace phi thương mại"),
"hypit-ai/hypit": ("Agent skill 'clone' video viral: footage, caption, B-roll, effect neo theo TỪ (SVML), WhisperX align", "✅ CPU phần dựng (gen model tuỳ chọn/API)", "★★★", "Ý tưởng neo B-roll/caption theo từ rất hợp; còn mới, cần thử; license Apache sửa đổi (cấm multi-tenant SaaS)", "Apache-2.0 sửa đổi"),
"Wan-Video/Wan2.2": ("Model video Wan 2.2 (T2V/I2V/TI2V-5B, A14B MoE)", "❌ GPU (TI2V-5B ~24GB; A14B ~80GB)", "★", "Chỉ qua API/cloud nếu cần B-roll AI", None),
"Wan-Video/Wan2.1": ("Model video Wan 2.1 (T2V-1.3B / 14B, I2V, VACE)", "❌ GPU (1.3B cần ~8.2GB VRAM)", "★", "Không chạy trên box CPU", None),
"WEIFENG2333/VideoCaptioner": ("Trợ lý phụ đề LLM: ASR → ngắt câu thông minh → sửa lỗi → dịch → xuất/burn", "✅ CPU (ASR whisper.cpp/faster-whisper hoặc API)", "★★★", "Ý tưởng ngắt câu bằng LLM hay; chủ yếu GUI, GPL-3.0", None),
"chatfire-AI/huobao-drama": ("Nền tảng tạo phim ngắn (短剧) từ 1 câu: kịch bản → nhân vật → ảnh/video AI → ghép", "⚠️ Cần API/GPU cho gen", "★", "Khác thể loại; CC BY-NC-SA 4.0 (phi thương mại)", "CC BY-NC-SA 4.0"),
"duixcom/Duix-Avatar": ("Avatar/digital human offline (HeyGem): clone người thật từ video, tạo video khẩu hình theo audio", "❌ GPU NVIDIA + Docker, 30–100GB đĩa", "★★", "Đúng bài toán 'presenter nói theo TTS' nhưng cần máy GPU riêng; license cộng đồng riêng", "Duix Community License"),
"k2-fsa/sherpa-onnx": ("ASR/TTS/VAD/diarization trên onnxruntime, không cần mạng, chạy được cả mobile", "✅ CPU tốt", "★★", "Phương án ASR/VAD nhẹ dự phòng", None),
"Zulko/moviepy": ("Thư viện dựng video Python (cắt, ghép, overlay, text, audio) v2", "✅ CPU (render 60s 1080×1920 mất vài phút)", "★★★★", "Keo Python dễ nhất cho PIP/B-roll/ghép âm; dự phòng khi không dùng HyperFrames", None),
"OpenTalker/SadTalker": ("Ảnh tĩnh + audio → video talking head (3DMM)", "⚠️ GPU (CPU rất chậm)", "★", "Ngừng cập nhật từ 2023; ta có clip thật nên không cần", "Apache-2.0 (+ thành phần bên thứ 3)"),
"FujiwaraChoki/MoneyPrinter": ("Bản gốc: tự tạo YouTube Shorts bằng MoviePy + stock footage", "✅ CPU", "★★", "Đã bị MoneyPrinterTurbo vượt; chỉ tham khảo", None),
"Rudrabha/Wav2Lip": ("Lip-sync: video mặt + audio → miệng khớp lời", "⚠️ GPU khuyến nghị; CPU chạy được nhưng chậm, mặt 96px mờ", "★★", "Có thể khớp môi presenter với giọng OmniVoice; CHỈ dùng nghiên cứu/cá nhân (model train trên LRS2)", "Phi thương mại (README)"),
"zai-org/CogVideo": ("CogVideoX 2B/5B text/image-to-video", "❌ GPU (≥4–10GB VRAM với diffusers, rất chậm)", "★", "Không thực tế trên CPU", None),
"Tencent-Hunyuan/HunyuanVideo": ("HunyuanVideo 13B text-to-video", "❌ GPU 45–80GB", "★", "Không chạy trên box; license Tencent (không áp dụng EU/UK/KR)", "Tencent Hunyuan Community"),
"krillinai/OpenCreator": ("Workspace AI cho creator (trước là KrillinAI): dịch/lồng tiếng video, avatar, edit", "⚠️ CPU + nhiều API", "★★", "Mạnh về dịch/lồng tiếng; không trọng tâm short tin tức", None),
"HKUDS/ViMax": ("Video agentic: đạo diễn/biên kịch/producer + model gen video", "❌ Cần API/GPU gen video", "★", "Thiên về phim AI, không phải tin + footage", None),
"elebumm/RedditVideoMakerBot": ("Bài Reddit → TTS + screenshot + video nền → MP4", "✅ CPU", "★", "Format khác (Reddit); GPL-3.0", None),
"linyqh/NarratoAI": ("LLM xem video có sẵn → viết lời bình → cắt cảnh khớp lời → TTS → phụ đề", "✅ CPU (≥4 core, 8GB RAM)", "★★★", "Hợp dạng 'bình luận clip demo/keynote'; tham khảo logic khớp cảnh ↔ lời", None),
"kkroening/ffmpeg-python": ("Wrapper Python cho ffmpeg, dựng filter_complex dạng graph", "✅ CPU", "★★★", "Không còn commit từ 2022 nhưng ổn định; tiện cho PIP overlay + loudnorm", None),
"Lightricks/LTX-Video": ("LTX-Video 2B/13B, nhanh, có bản distilled/fp8", "❌ GPU (bản nhỏ vài GB VRAM; CPU offload chỉ một phần)", "★", "Model video mở 'nhẹ' nhất nhưng vẫn cần GPU", "Apache-2.0 (code) + OpenRail-M (weights)"),
"anliyuan/Ultralight-Digital-Human": ("Digital human siêu nhẹ, chạy realtime trên mobile; train trên video 3–5 phút của 1 người", "⚠️ Train cần GPU; infer có thể CPU", "★★", "Ứng viên lip-sync CPU duy nhất; KHÔNG có license → rủi ro pháp lý", "Không có license"),
"lipku/LiveTalking": ("Digital human tương tác realtime (wav2lip/musetalk/ernerf) qua WebRTC", "❌ GPU", "★", "Cho livestream, không cần cho render offline", None),
"Lightricks/LTX-2": ("LTX-2/2.5: model sinh audio+video đồng bộ", "❌ GPU lớn (có fp8 + offload)", "★", "Không chạy trên box", "LTX Community License"),
"fudan-generative-vision/hallo": ("Ảnh chân dung + audio → video nói (diffusion)", "❌ GPU", "★", "Không cần cho pipeline", None),
"RayVentura/ShortGPT": ("Framework tự động YouTube Shorts/TikTok: script, TTS, footage, caption, dịch", "✅ CPU", "★★", "Commit cuối 02/2025 – gần như ngừng; chỉ tham khảo", None),
"OpenTalker/video-retalking": ("Lip-sync video talking head theo audio, chỉnh biểu cảm", "❌ GPU", "★", "Ngừng từ 2023", None),
"TMElyralab/MuseTalk": ("Lip-sync realtime bằng latent inpainting, chất lượng cao hơn Wav2Lip", "❌ GPU (4GB VRAM: ~5 phút cho 8s)", "★★", "Lip-sync tốt nhất nếu thuê GPU; code MIT (kiểm tra license từng model)", "MIT (code)"),
"modelscope/FunClip": ("FunASR nhận dạng → chọn đoạn bằng text/LLM → cắt clip + phụ đề, Gradio UI", "✅ CPU", "★★", "ASR FunASR mạnh tiếng Trung, tiếng Việt yếu", None),
"bytedance/LatentSync": ("Lip-sync dựa trên Stable Diffusion, chất lượng cao", "❌ GPU 8–18GB VRAM", "★", "Không chạy trên box", None),
"mifi/editly": ("Dựng video khai báo bằng JSON5 (clip, text, transition) → ffmpeg; CLI + API Node", "✅ CPU", "★★★", "Đơn giản cho slideshow/B-roll; commit cuối 02/2025", None),
"WyattBlue/auto-editor": ("Tự cắt khoảng lặng/đoạn thừa theo âm lượng/chuyển động; xuất MP4 hoặc timeline Premiere/Resolve", "✅ CPU, rất nhanh", "★★★★", "Cắt lặng clip presenter / voice trước khi dựng; Unlicense", None),
"nexu-io/html-video": ("HTML/CSS/data → MP4 cho coding agent, engine render thay được, 21 template", "✅ CPU", "★★", "Cùng ý tưởng HyperFrames nhưng nhỏ hơn", None),
"redotvideo/revideo": ("Fork Motion Canvas để render headless/API (TS → MP4)", "✅ CPU", "★★", "Thay thế Remotion có license MIT; cộng đồng nhỏ hơn", None),
"PyAV-Org/PyAV": ("Binding Python cấp thấp cho thư viện FFmpeg", "✅ CPU", "★★", "Dùng khi cần xử lý frame trực tiếp", None),
"diffusionstudio/core": ("Engine compositing video chạy trong trình duyệt (WebCodecs)", "✅ CPU/browser", "★", "Hợp app web, không hợp pipeline server", None),
"m1guelpf/auto-subtitle": ("Whisper + ffmpeg: tạo và burn phụ đề vào video bằng 1 lệnh", "⚠️ CPU chậm (whisper gốc)", "★★", "Ngừng từ 2023; tự viết bằng faster-whisper còn tốt hơn", None),
"tmoroney/auto-subs": ("Tạo phụ đề on-device, cắm thẳng vào DaVinci Resolve/Premiere/After Effects", "✅ CPU", "★", "Cho dựng tay trên NLE, không cho pipeline headless", None),
"jianfch/stable-ts": ("Whisper + forced alignment, chỉnh timestamp ổn định", "✅ CPU", "★★", "ĐÃ ARCHIVED → tránh, dùng WhisperX", None),
"VinAIResearch/PhoWhisper": ("Whisper fine-tune cho tiếng Việt (VinAI), weights trên HuggingFace", "✅ CPU (tiny/base/small; convert CTranslate2)", "★★★", "ASR tiếng Việt tốt nhất để nhận dạng clip nguồn; repo chỉ chứa info, weights ở HF", None),
"ClipsAI/clipsai": ("Thư viện Python tự cắt clip từ video dài theo transcript + resize 16:9→9:16 theo người nói", "⚠️ CPU được (WhisperX + pyannote)", "★★", "Ngừng từ 01/2024; ý tưởng auto-reframe 9:16 hữu ích", None),
"Anil-matcha/AI-Youtube-Shorts-Generator": ("Video YouTube dài → LLM chọn highlight → Whisper → crop mặt 9:16 → shorts", "✅ CPU (LLM qua API)", "★★★", "Dùng khi muốn cắt đoạn keynote/podcast làm B-roll/nguồn tin", None),
"RafaelGodoyEbert/ViralCutter": ("YouTube → clip viral 9:16 có transcript + phụ đề", "⚠️ CPU chậm, GPU khuyến nghị", "★★", "GPL-3.0; giống AI-Youtube-Shorts-Generator", None),
"antgroup/echomimic_v2": ("Ảnh + audio → video bán thân nói + cử chỉ", "❌ GPU", "★", "Không chạy trên box", None),
"Tencent-Hunyuan/HunyuanVideo-1.5": ("HunyuanVideo 1.5 (8.3B), nhẹ hơn bản gốc", "❌ GPU ≥14GB (offload)", "★", "Không chạy trên box", "Tencent Hunyuan Community"),
"genmoai/mochi": ("Mochi 1 (10B) text-to-video", "❌ GPU ~60GB (1 GPU)", "★", "Không chạy trên box", None),
"hao-ai-lab/FastVideo": ("Framework tăng tốc inference/post-train model video (Wan, Hunyuan…)", "❌ GPU", "★", "Chỉ hữu ích khi có GPU", None),
"FireRedTeam/FireRed-OpenStoryline": ("Agent edit video bằng ngôn ngữ tự nhiên (chọn cảnh, nhạc, phụ đề)", "⚠️ CPU + LLM/VLM API", "★★", "Tham khảo workflow 'edit theo ý định'", None),
"SamurAIGPT/Text-To-Video-AI": ("Text → script → TTS → tìm video Pexels → caption → ghép", "✅ CPU", "★★", "Bản tối giản dễ đọc của ý tưởng MoneyPrinterTurbo", None),
"GuanYixuan/pyJianYingDraft": ("Python sinh draft 剪映/CapCut (track, text, effect) để mở/xuất trong app", "✅ CPU (cần app JianYing/CapCut Windows/mac để xuất)", "★★", "Hợp nếu muốn người dựng tinh chỉnh trên CapCut; không render trên Linux", None),
"yt-dlp/yt-dlp": ("Tải video/audio từ YouTube, TikTok, X… (cắt theo đoạn --download-sections, chọn chất lượng)", "✅ CPU", "★★★★", "Lấy clip nguồn tin (demo, keynote) làm B-roll; cẩn thận bản quyền, chỉ dùng đoạn ngắn + ghi nguồn", None),
"Breakthrough/PySceneDetect": ("Phát hiện điểm cắt cảnh (content/adaptive/threshold) → tách clip, xuất timecode", "✅ CPU, nhanh", "★★★★", "Chặt video nguồn thành shot 1–3s để chèn B-roll; chọn shot đẹp tự động", None),
"mlfoundations/open_clip": ("CLIP mã nguồn mở: embedding ảnh/text để tìm ảnh/khung hình theo mô tả", "✅ CPU (ViT-B/32 nhẹ)", "★★★", "Xếp hạng footage Pexels/khung hình theo câu kịch bản (semantic B-roll matching)", "MIT-style (custom)"),
}
